### ISSUE TITLE
TypeScript Compatibility

### ISSUE THREAD

**Issue by SOG-web** [FriendsOfReact/react-native-gradients#15]
Try `npm i --save-dev @types/react-native-gradients` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-gradients';`

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-native-gradients - Not found
npm ERR! 404
npm ERR! 404  '@types/react-native-gradients@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

please is there any solution

**Comment by yildizberkay** [comment]
Hello @SOG-web

I've updated it for TS support. Thank you for your feedback.

https://github.com/FriendsOfReact/react-native-gradients/pull/18

**Comment by yildizberkay** [comment]
Hello @SOG-web

I've updated it for TS support. Thank you for your feedback.

https://github.com/FriendsOfReact/react-native-gradients/pull/18
