### ISSUE TITLE
Compatibility with `react-native-svg` 13+

### ISSUE THREAD

**Issue by fahad86** [FriendsOfReact/react-native-gradients#16]
After upgrading to `react-native-svg` to 13.0.0 and when react-native-gradients is used with multiple instances (e.g. in a list view), I'm getting an errors saying:

**Uncaught Error**

`Tried to register two views with the same name RNSVGSvgView`

and in the console I get the message:

` ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[16], "./NativeComponents").RNSVGSvg')`

**Comment by pfcodes** [comment]
are there plans to update this package so modifying package.json isn't needed?
