### ISSUE TITLE
Missing key props

### ISSUE THREAD

**Issue by silvestreh** [FriendsOfReact/react-native-gradients#5]
Hey there, I noticed you're missing the `key` prop when mapping the `colorList` array.

https://github.com/FriendsOfReact/react-native-gradients/blob/master/src/LinearGradient.js#L22
https://github.com/FriendsOfReact/react-native-gradients/blob/master/src/RadialGradient.js#L21

**Comment by yildizberkay** [comment]
Thank you very much, it is fixed with #7.
